### ISSUE TITLE
CLI commands for Mac - Pre-requisites

### ISSUE THREAD

**Issue by xerosum** [azurecitadel/azurecitadel.github.io#29]
Perhaps worth mentioning, per 'These commands are as tested within the Windows Subsystem for Linux (WSL), with the CLI 2.0 added.' -- nearly everything works on MacOS (High Sierra, with the Azure CLI and Homebrew installed), at least as far as lab 4.

The one command which fails is `job=job.$(date --utc +"%Y%m%d.%H%M")`, because Linux uses the GNU version of the date command and MacOS uses the UNIX version. 

Easy fix: `brew install coreutils`, and use `gdate` instead of `date`. Further details [here](https://stackoverflow.com/questions/9804966/date-command-does-not-follow-linux-specifications-mac-os-x-lion).

**Comment by visheshbalani** [comment]
Hi

I was trying to run the AKS Lab and am stuck on module 2 -  https://azurecitadel.github.io/labs/kubernetes/part2/ .
The command 
az acr build --registry $ACR_NAME -g kube-lab --context . --file node/data-api/Dockerfile --image smilr/data-api 
returns an error

No module named 'pytz'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 251, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 244, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 140, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 76, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 425, in default_arguments_loader
    op = handler or self.get_op_handler(operation)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 469, in get_op_handler
    op = import_module(mod_to_import)
  File "/opt/az/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/<user>/.azure/cliextensions/acrbuildext/azext_acrbuildext/build.py", line 18, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'

I have installed python3.6, set it as default and even tried using a virtualenv. I have imported pytz in the python terminal with all 3 versions of python that I have on WSL. Please have a look and let me know if I'm doing something wrong. Any help would be appreciated @benc-uk @xerosum @richeney @azurecitadel

**Comment by benc-uk** [comment]
@visheshbalani Thanks for the feedback.
I think this error is coming from ACR, and from the ACR build workers up in Azure, I don't think it is related to the config of your local machine.
ACR build feature is still in preview and know it's undergoing some changes. 
I'll take a look at the error next week and see if I can reproduce

**Comment by visheshbalani** [comment]
Thanks for the prompt reply Ben!
I moved on with the tutorial in the meantime by building the images with the docker command and then pushed them to ACR.

**Comment by benc-uk** [comment]
Great! Glad it hasn't blocked you.
Public images are available, but having them in ACR is more realistic

**Comment by rhollins** [comment]
I'm having exactly same issue as @visheshbalani today but on Windows 10, running just "az acr build" results in:

```
No module named 'pytz'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 262, in execute
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\__init__.py", line 253, in load_arguments
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 141, in load_arguments
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\commands.py", line 76, in load_arguments
    cmd_args = self.arguments_loader()
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\__init__.py", line 440, in default_arguments_loader
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\__init__.py", line 485, in get_op_handler
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\<my username>\.azure\cliextensions\acrbuildext\azext_acrbuildext\build.py", line 18, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'
```

**Comment by benc-uk** [comment]
@idelix - which version of the Azure CLI do you have installed?. I just tried `az acr build` on my Window 10 machine and got no error. I'm on version **2.0.41**

Note. You should never need to install Python to use the Azure CLI, it installs it's own private version of Python and uses that

**Comment by rhollins** [comment]
Hi, 

So it failed with cli-2.0.43 on my desktop then I upgraded to cli-2.0.45 and it seems to work file, but I think this might be more to do with my development machine then cli.

**Comment by richeney** [comment]
Having read these comments it sounds as if they have been addressed (usually via updating the CLI!) so I will close.
